### ISSUE TITLE
Can use SDL2.framework bundle instead of pkg-config sdl2

### ISSUE THREAD

**Issue by jakwings** [61315/resynthesizer#1]
This is great work! Thank you!

I downloaded SDL2.framework from https://libsdl.org/ and substitute the `pkg-config` flags with `-F ~/Library/Frameworks -framework SDL2` and `examples/painter` and `examples/ppm` works, but `examples/hello` doesn't spew out any warning.

**Comment by miinso** [comment]
It [now](https://github.com/61315/resynthesizer/commit/f55fb2a9f9415575b4088f2f2014e505f5db30fe) spews out something! Thanks for the catch @iology  :)
> `IMAGE_SYNTH_SUCCESS`

And yes, it should work with the framework bundle. Updated the `README.md` accordingly.

> ##### Using disk image:
> - Download installation package from the [site](https://libsdl.org/download-2.0.php).
> 
> ```
> $ make examples/painter LDFLAG="-F/Library/Frameworks -framework SDL2"
> $ examples/painter <source>
> ```
