### ISSUE TITLE
 How is wasm compiled?

### ISSUE THREAD

**Issue by ByteCanva** [61315/resynthesizer#4]

**Comment by miinso** [comment]
I'm assuming you already have the emcc installed someplace.

It starts with compiling each source into emcc object files.

```
emcc -DSYNTH_LIB_ALONE -O3 -s resynthesizer/engine.c -c -o engine.o
emcc -DSYNTH_LIB_ALONE -O3 -s resynthesizer/engineParams.c -c -o engineParams.o
emcc -DSYNTH_LIB_ALONE -O3 -s resynthesizer/glibProxy.c -c -o glibProxy.o
emcc -DSYNTH_LIB_ALONE -O3 -s resynthesizer/imageFormat.c -c -o imageFormat.o
emcc -DSYNTH_LIB_ALONE -O3 -s resynthesizer/imageSynth.c -c -o imageSynth.o
emcc -DSYNTH_LIB_ALONE -O3 -s resynthesizer/progress.c -c -o progress.o
```

And assemble them into a library.

```
emar rcs libresynthesizer.a engine.o engineParams.o glibProxy.o imageFormat.o imageSynth.o progress.o
```

And then compile the sample program (painter_wasm.c) while linking against the built library. `libresynthesizer.a` in this case.

```
emcc -O3 -flto -o interactive.html examples/painter_wasm.c -Iresynthesizer libresynthesizer.a -s USE_SDL=2 --preload-file=assets/source001.ppm
```

Then you get a nice, cool-looking interactive demo. ;)

If you need help with anything else, you can read the emscripten manual. 
https://emscripten.org/docs/getting_started/Tutorial.html

**Comment by ByteCanva** [comment]
wow!Thank you very much!
