### ISSUE TITLE
python library here

### ISSUE THREAD

**Issue by light-and-ray** [61315/resynthesizer#6]
Hello again. I've wrapped it into python library: https://github.com/light-and-ray/resynthesizer-python-lib I think I'll build it for windows, and pack into wheel and add into pip

Btw, you use Mac, if you're interested, can you give me a build for it

**Comment by miinso** [comment]
```
libresynthesizer.zip
├── libresynthesizer_arm.dylib
├── libresynthesizer_intel.dylib
└── libresynthesizer_universal.dylib
```
[libresynthesizer.zip](https://github.com/user-attachments/files/16169594/libresynthesizer.zip)

**Comment by light-and-ray** [comment]
Nice: https://pypi.org/project/resynthesizer/
